# Generated by Django 3.0.5 on 2023-12-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Emergencia Medicos Especialistas', 'Emergency Medicine Specialists'), ('Allergista/Imunologista', 'Alergista/Imunologista'), ('Anestesiologista', 'Anestesiologista'), ('Cirurgioes de Colon', 'Cirurgioes de Colon')], default='Cardiologist', max_length=50),
        ),
    ]
